import { fireEvent, render } from "@testing-library/react"
import { vi } from "vitest"

vi.mock("@noriginmedia/norigin-spatial-navigation", () => ({
  useFocusable: ({ onEnterPress }: { onEnterPress?: () => void }) => ({
    ref: { current: null },
    focused: false,
    triggerEnter: onEnterPress,
  }),
}))

import { Focusable } from "./Focusable"

it("ignores the synthetic click generated by remote Enter", () => {
  const onEnter = vi.fn()
  const { getByRole } = render(<Focusable onEnter={onEnter}>Key</Focusable>)
  fireEvent.click(getByRole("button"), { detail: 0 })
  expect(onEnter).not.toHaveBeenCalled()
})

it("still supports real pointer clicks in desktop development", () => {
  const onEnter = vi.fn()
  const { getByRole } = render(<Focusable onEnter={onEnter}>Key</Focusable>)
  fireEvent.click(getByRole("button"), { detail: 1 })
  expect(onEnter).toHaveBeenCalledOnce()
})
